config/routes.rb
Rails.application.routes.draw do
  post 'salles/cree_et_ajoute_dans_meme_lieu', to: 'salles#cree_et_ajoute', as: :cree_salle_et_ajoute_dans_meme_lieu
  root 'pages#home'
  get 'a-propos', to: 'pages#apropos'
  get 'stats', to: 'pages#stats'

  resources :salles do
    collection do
      get 'brut'
      get 'prospects'
      get 'prequalifiees'
    end
  end
  get 'salles/:id/contact/:demande_id', to: 'salles#contact', as: :contacte_demandeur
  resources :propositions_salles, only: [:new, :create]
  resource :salles_import, only: [:new, :create]

  resources :demandes, only: [:new, :create, :show, :index], param: :secret_id
  post 'demandes/:secret_id/cloture', to: 'demandes#cloture', as: :cloture_demande
  get 'demandes/:secret_id/autres_salles_correspondantes', to: 'demandes#autres_salles_correspondantes', as: :autres_salles_correspondantes
  post 'demandes/:secret_id/notifie/:salle_id', to: 'demandes#notifie', as: :notifie_demande
  mount LetterOpenerWeb::Engine, at: '/mails'
end

app/views/pages/apropos.html.haml
.ui.main.container.relaxed
  %h2 A propos

  %h3 Vite un lieu, c'est quoi ?

  %p
    %i Vite un lieu
    est une plateforme développée par la Ville de Paris dans le cadre du programme Startup de Ville. Fruit du travail de terrain d'agents de la Ville ayant passé de nombreuses années au contact des associations, elle a pour objectif de vous permettre de trouver rapidement une salle, ou plus largement un espace correspondant à vos besoins dans le cadre d'activités que vous souhaitez organiser.
  %p
    Il peut s'agir à titre d'exemples de réunions de conseil d'administration, d'assemblées générales, de groupes de travail, de formations, de réunions publiques d'information, de répétitions de spectacle, de cours de yoga, de soutien scolaire...

  %h3 Qui sommes-nous ?

  %p
    %i Vite un lieu
    est une <a href="http://missioncapitale.paris.fr/57/horizons/lactu-de-la-ville/lancement-de-start-up-de-ville/">Startup de Ville</a>. Nous sommes un service public numérique de la Ville de Paris produit par une petite équipe autonome. Nous appliquons les pratiques des startups du numérique au service de l’action publique. Le programme Startup de Ville s'inspire de la philosophie, des principes, et de l'expérience des <a href="https://beta.gouv.fr">Startups d'Etat de l'Incubateur de Services Numériques</a> au sein du Secrétariat Général pour la Modernisation de l'Action Publique auprès du Premier Ministre.

app/views/pages/home.html.haml
.ui.vertical.masthead.center.aligned.inverted.segment
  .ui.container
    .ui.large.secondary.inverted.pointing.menu
      %a.toc.item
        %i.sidebar.icon
      %a.active.item{:href => "/"}
        Accueil
      =link_to a_propos_path, class: 'item' do
        A propos
        = image_tag 'mairie-de-paris.png', class: 'logo-secondary ui'
      .right.item= link_to 'Proposer une salle', new_propositions_salle_path, class: 'ui inverted button'
  .ui.justified.container
    %h1#nom-produit.ui.inverted.header
      Vite, un lieu !
    %h2#proposition-valeur
      Vous êtes une association ?
      %br
      Paris vous aide à trouver une salle pour
      %br
      vos réunions, vos événements, vos activités collectives
    #cta
      - if ENV["STANDBY"] == "true"
        .ui.icon.teal.large.message
          %i.announcement.icon
          .content
            .header
              Le service "Vite un lieu" est en pause !
            %p
              Nous sommes fiers de vous annoncer que La Startup de Ville "Vite un lieu !" a trouvé ses premiers usagers satifsaits ! Nous mettons en pause pour l'instant notre service pour préparer le passage à l'échelle à l'ensemble de la Ville de Paris
      - else
        = link_to 'Déposer une demande', new_demande_path, class: 'ui teal right button huge'

app/views/pages/stats.html.haml
.ui.main.container.relaxed
  %h2 Statistiques

  .nb_demandes.ui.statistic
    .value= @nb_demandes
    .label demandes