config/routes.rb
Rails.application.routes.draw do
  post 'salles/cree_et_ajoute_dans_meme_lieu', to: 'salles#cree_et_ajoute', as: :cree_salle_et_ajoute_dans_meme_lieu
  root 'pages#home'
  get 'a-propos', to: 'pages#apropos'
  get 'stats', to: 'pages#stats'

  resources :salles do
    collection do
      get 'brut'
      get 'prospects'
      get 'prequalifiees'
    end
  end
  get 'salles/:id/contact/:demande_id', to: 'salles#contact', as: :contacte_demandeur
  resources :propositions_salles, only: [:new, :create]
  resource :salles_import, only: [:new, :create]

  resources :demandes, only: [:new, :create, :show, :index], param: :secret_id
  post 'demandes/:secret_id/cloture', to: 'demandes#cloture', as: :cloture_demande
  get 'demandes/:secret_id/autres_salles_correspondantes', to: 'demandes#autres_salles_correspondantes', as: :autres_salles_correspondantes
  post 'demandes/:secret_id/notifie/:salle_id', to: 'demandes#notifie', as: :notifie_demande
  mount LetterOpenerWeb::Engine, at: '/mails'
end

app/models/salle.rb
class Salle < ApplicationRecord
  validates :nom_salle, uniqueness: { scope: :nom_lieu }
  validates :nom_lieu, :adresse, :ville, :code_postal, presence: true
  has_many :notifications
  has_many :contacts

  before_save :affecte_capacite!
  before_save :calcule_coordonnees!, if: ->(salle){ salle.adresse_changed? }

  scope :confirmees, -> { where(qualification: :qualifiee) }
  scope :non_confirmees, -> { where.not(qualification: :qualifiee) }
  scope :brut, -> { where(qualification: :brut) }
  scope :prospects, -> { where(qualification: :prospect) }
  scope :prequalifiees, -> { where(qualification: :prequalifiee) }

  geocoded_by :adresse_complete

  AVEC_TABLES = :avec_tables
  ASSEMBLEE = :assemblee

  QUALIFICATIONS = [:brut, :prospect, :prequalifiee]

  def affecte_capacite!
    capacite_assemblee = self.capacite_assemblee || 0
    capacite_avec_tables = self.capacite_avec_tables || 0
    capacite_cocktail = self.capacite_cocktail || 0
    max = [capacite_assemblee, capacite_avec_tables, capacite_cocktail].max || 0
    self.capacite = max if self.capacite.nil? || max > self.capacite
  end

  def calcule_coordonnees!
    salles_meme_adresse_geocodee = Salle.where(adresse: self.adresse, code_postal: self.code_postal, ville: self.ville).where('latitude is not null')
    if salles_meme_adresse_geocodee.present?
      salle = salles_meme_adresse_geocodee.first
      self.latitude, self.longitude = salle.latitude, salle.longitude
    else
      coordonnees = GeocoderAdresse.new(self.adresse_complete).call
      if coordonnees[:latitude].present? && coordonnees[:longitude].present?
        self.latitude = coordonnees[:latitude]
        self.longitude = coordonnees[:longitude]
      end
    end
  end

  def nom
    [ self.nom_lieu, self.nom_salle ].join(' - ')
  end

  def adresse_complete
    code_postal_et_ville = [ self.code_postal, self.ville ].join(' ')
    [self.adresse, code_postal_et_ville].join(', ')
  end

  def draft?
    QUALIFICATIONS.include? self.qualification.to_sym
  end

  def notifie?(demande)
    notifications_demande(demande).present?
  end

  def notifications_demande(demande)
    self.notifications.where(demande: demande)
  end

  def contacts_demande(demande)
    self.contacts.where(demande: demande)
  end

  def statut(demande)
    return :a_pris_contact if contacts_demande(demande).present?
    return :notifiee if notifications_demande(demande).present?
    :a_traiter
  end

  def evenements(demande)
    evenements = []
    notifications_demande(demande).each do |notif|
      evenements << { type: :notifie, quand: notif.created_at }
    end

    contacts_demande(demande).each do |contact|
      evenements << { type: :a_pris_contact, quand: contact.created_at }
    end

    evenements
  end

  def date_derniere_notif(demande)
    notifications_demande(demande).last.created_at
  end
end

app/controllers/salles_controller.rb
class SallesController < ApplicationController
  http_basic_authenticate_with name: ENV['ADMIN_USER'], password: ENV['ADMIN_PASSWORD']
  before_action :set_salle, only: [:show, :edit, :update, :destroy, :contact]

  def index
    liste Salle.confirmees
  end

  def brut
    liste Salle.brut
  end

  def prospects
    liste Salle.prospects
  end

  def prequalifiees
    liste Salle.prequalifiees
  end

  def show
  end

  def new
    @salle = Salle.new
  end

  def edit
  end

  def create
    if params[:commit] == t('salles.creation_et_ajout_submit')
      cree_et_ajoute
    else
      cree
    end
  end

  def cree
    @salle = ProposerSalle.new(salle_params).call!
    if @salle.valid?
        redirect_to salles_path, notice: "La salle #{@salle.nom} vient d'être créé"
    else
      render :new
    end
  end

  def cree_et_ajoute
    salle_modele = ProposerSalle.new(salle_params).call!
    if salle_modele.valid?
      @salle = Salle.new(nom_lieu: salle_modele.nom_lieu, email: salle_modele.email, tel: salle_modele.tel, adresse: salle_modele.adresse)
    else
      @salle = salle_modele
    end
    render :new
  end

  def contact
    contact = ContacterDemandeur.new(@salle, params[:demande_id])
    if contact.call!
      @demande = contact.demande
    else
      render 'contact_demande_cloturee'
    end
  end

  def update
    if params[:commit] == t('salles.validation_submit')
      params[:salle][:qualification] = "qualifiee"
    end
    if @salle.update(salle_params)
        redirect_to salles_path, notice: 'La salle a été modifiée avec succès'
    else
      render :edit
    end
  end

  def destroy
    @salle.destroy
    redirect_to salles_url, notice: 'La salle a été correctement supprimée !'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salle
      @salle = Salle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salle_params
      params.require(:salle).
        permit(:qualification, :nom_lieu, :nom_salle,
               :adresse, :code_postal, :ville, :email, :tel, :horaires_ouverture,
               :superficie, :capacite, :capacite_assemblee, :capacite_avec_tables, :capacite_cocktail,
               :tarif_heure, :tarif_demi_journee, :tarif_journee, :temps_min_reservation,
               :activites, :precisions)
    end

    def liste(salles)
      @salles = ChercherSalles.new(params, salles).call
      @nb_salles_trouvees = @salles.length
      respond_to do |format|
        format.csv do
          ExporterSalles.new("export.csv", @salles).call!
          render file: "export.csv"
        end
        format.html do
          @salles = @salles.page params[:page]
          render :index
        end
      end
    end
end

app/views/salles/_form.html.haml
= form_for @salle, url: url,  html: { class: 'ui large form container salle' } do |f|
  - if @salle.errors.any?
    #explication_erreurs.ui.negative.message
      .header= "Impossible de proposer la salle"
      %ul.list
        - @salle.errors.full_messages.each do |message|
          %li= message
  .inline.fields
    = f.label "Niveau de qualification"
    .field
      .ui.radio.checkbox
        = f.radio_button :qualification, "brut"
        = f.label "Brut"
    .field
      .ui.radio.checkbox
        = f.radio_button :qualification, "prospect"
        = f.label "Prospect"
    .field
      .ui.radio.checkbox
        = f.radio_button :qualification, "prequalifiee"
        = f.label "Pre-qualifiée"
  .inline.fields
    .required.field
      = f.label :nom_lieu
      = f.text_field :nom_lieu
    .required.field
      = f.label :nom_salle
      = f.text_field :nom_salle
  .inline.fields
    .required.field
      = f.label :adresse
      = f.text_field :adresse
    .required.field
      = f.label :code_postal
      = f.text_field :code_postal, size: 5
    .required.field
      = f.label :ville
      = f.text_field :ville
  .inline.fields
    .required.field
      = f.label :email
      = f.text_field :email
    .required.field
      = f.label :tel
      = f.text_field :tel
    .required.field
      = f.label :web
      = f.text_field :web
  .field
    = f.label     :horaires_ouverture
    = f.text_area :horaires_ouverture, rows: 2
  .inline.fields
    .required.field
      = f.label :superficie
      = f.number_field :superficie
    .required.field
      = f.label :capacite
      = f.number_field :capacite
    .field
      = f.label :capacite_assemblee
      = f.number_field :capacite_assemblee

    .field
      = f.label :capacite_avec_tables
      = f.number_field :capacite_avec_tables
    .field
      = f.label :capacite_cocktail
      = f.number_field :capacite_cocktail
  .fields
    .field
      = f.label :tarif_heure
      = f.number_field :tarif_heure
    .field
      = f.label :tarif_demi_journee
      = f.number_field :tarif_demi_journee
    .field
      = f.label :tarif_journee
      = f.number_field :tarif_journee
    .field
      = f.label :temps_min_reservation, "Temps min réservation (h)"
      = f.number_field :temps_min_reservation
  .field
    = f.label :activites, "Type d'activités acceptées"
    = f.text_field :activites
  .field
    = f.label :precisions
    = f.text_area :precisions, rows: 2
  .actions
    = f.submit label_premier_submit, class: 'ui submit button teal huge'
    - if defined? label_second_submit
      = f.submit label_second_submit, class: 'ui submit button huge'
    - if @salle.draft?
      = f.submit t('salles.validation_submit'), class: 'ui submit button huge'

app/views/salles/_liste.html.haml
%table.ui.striped.table
  %thead
    %tr
      %td Nom
      %td Capacité
      %td Tarif minimum
      %td Tel
      %td Email
      %td Horaires ouverture
      %td Activites
      %td Adresse
      %td Precisions
  %tbody.salles
    - @salles.each do |salle|
      %tr.salle
        %td.nom= salle.nom
        %td= salle.capacite
        %td= salle.tarif_minimum
        %td= salle.tel
        %td= salle.email
        %td= salle.horaires_ouverture
        %td= salle.activites
        %td= salle.adresse
        %td= salle.precisions
        %td= link_to 'Editer', edit_salle_path(salle), class: 'ui button'

app/views/salles/contact.html.haml
.ui.container.main.relaxed
  .ui.stackable.grid
    .five.wide.column
      .demande.ui.card
        .content
          .header= "Demande de salle déposée le #{l(@demande.created_at.to_date)}"
          .meta
            = "#{@demande.nom_association} (#{@demande.nom_demandeur})"
          .meta= @demande.email_demandeur
          .meta= @demande.tel_demandeur
          .description
            = @demande.nb_participants
            participants
            %br
            Date :
            = @demande.date
            %br
            Duree :
            = @demande.duree
            %br
            Budget :
            = @demande.budget
            €
            %br
            Precisions :
            = @demande.activite
    .eleven.wide.column
      %header.header
        %h1= @salle.nom
      .ui.raised.container.teal.huge.segment
        Vous pouvez contacter
        = @demande.nom_demandeur
        de l'association
        = @demande.nom_association
        %ul
          %li
            Par mail:
            = mail_to @demande.email_demandeur
          %li
            Par tel:
            = @demande.tel_demandeur

app/views/salles/contact_demande_cloturee.html.haml
.ui.grid.container.main.relaxed
  .ui.stacked.segment.attached.huge
    %h3
      Désolé ! Cette demande a déjà trouvé un lieu pour répondre à son besoin.
    %p
      Merci toutefois d'avoir manifesté de l'intérêt pour cette demande. Nous espérons qu'une prochaine demande puisse très prochainement être accueillie dans votre lieu.

app/views/salles/demande.html.haml
.ui.container.main.relaxed
  .ui.stackable.grid
    .five.wide.column
      .demande.ui.card
        .content
          .header= "Demande de salle déposée le #{l(@demande.created_at.to_date)}"
          .meta
            = "#{@demande.nom_association} (#{@demande.nom_demandeur})"
          .meta= @demande.email_demandeur
          .meta= @demande.tel_demandeur
          .description
            = @demande.nb_participants
            participants
            %br
            Date :
            = @demande.date
            %br
            Duree :
            = @demande.duree
            %br
            Budget :
            = @demande.budget
            €
            %br
            Precisions :
            = @demande.activite
    .eleven.wide.column
      %header.header
        %h1= @salle.nom
      .ui.stacked.teal.segment
        Vous pouvez contacter
        = @demande.nom_demandeur
        de l'association
        = @demande.nom_association
        %ul
          %li
            Par mail:
            = mail_to @demande.email_demandeur
          %li
            Par tel:
            = @demande.tel_demandeur

app/views/salles/edit.html.haml
.ui.main.container.relaxed
  %h2 Modifier une salle
  = render partial: 'form', locals: { url: salle_path(@salle), label_premier_submit: t('salles.edit_submit') }

app/views/salles/index.html.haml
.ui.container.main.relaxed
  %header.header
    %h1 Salles
    .ui.secondary.teal.menu
      = link_to salles_path, class: item_css_classes(salles_path) do
        Salles validées
        .ui.label= Salle.confirmees.count

      = link_to brut_salles_path, class: item_css_classes(brut_salles_path) do
        Salles brutes
        .ui.label= Salle.brut.count

      = link_to prospects_salles_path, class: item_css_classes(prospects_salles_path) do
        Salles prospects
        .ui.label= Salle.prospects.count

      = link_to prequalifiees_salles_path, class: item_css_classes(prequalifiees_salles_path) do
        Salles pré-qualifiées
        .ui.label= Salle.prequalifiees.count
      .ui.right.menu
        = link_to 'Importer des salles', new_salles_import_path, class: 'item'
        = link_to 'Ajouter une salle', new_salle_path, class: 'item'

  .ui.segment
    = form_tag request.path, method: :get, id: 'recherche_form', class: 'ui form' do
      .fields
        .field
          = label_tag :nom_lieu, 'Nom du lieu'
          = text_field_tag :nom_lieu, params[:nom_lieu], placeholder: 'Lieu'
        .field
          = label_tag :code_postal
          = text_field_tag :code_postal, params[:code_postal], placeholder: 'Code postal', size: 10
        .field
          = label_tag :capacite_min, 'Capacité min'
          = text_field_tag :capacite_min, params[:capacite_min]
        .field
          = label_tag :capacite_max, 'Capacité max'
          = text_field_tag :capacite_max, params[:capacite_max]
        .field
          = label_tag :source
          = text_field_tag :source, params[:source]
      = button_tag class: 'ui teal icon submit button' do
        Rechercher

        %i.search.icon
      = link_to 'Exporter', params.merge(format: :csv).permit(:nom_lieu, :code_postal, :source, :format), class: 'ui right button'
  .ui.horizontal.segments
    .ui.segment.basic
      .ui.large.header= "#{@nb_salles_trouvees} salles trouvées"
    .ui.segment.nav-pagination= paginate @salles

  %table.ui.striped.table
    %thead
      %tr
        %td Nom
        %td Capacité
        %td Tarif minimum
        %td Code Postal
        %td Source
    %tbody.salles
      - @salles.each do |salle|
        %tr.salle
          %td.nom= salle.nom
          %td= salle.capacite
          %td= salle.tarif_minimum
          %td= salle.code_postal
          %td= salle.source
          %td
            = link_to edit_salle_path(salle), class: 'ui icon button' do
              %i.class.edit.icon
          %td
            = link_to salle_path(salle), method: :delete, class: 'ui icon button' do
              %i.class.remove.icon
          - if salle.web.present?
            %td
              = link_to "http://#{salle.web}", target: '_blank', class: 'ui icon button' do
                %i.class.world.icon

  = paginate @salles

app/views/salles/new.html.haml
.ui.main.container.relaxed
  %h2 Créer une salle
  = render partial: 'form', locals: { url: salles_path, label_premier_submit: t('salles.creation_submit'), label_second_submit: t('salles.creation_et_ajout_submit') }

app/views/salles/show.html.haml
%p#notice= notice

%p
  %b Nom:
  = @salle.nom
%p
  %b Adresse:
  = @salle.adresse
%p
  %b Email:
  = @salle.email
%p
  %b Tel:
  = @salle.tel
%p
  %b Horaires ouverture:
  = @salle.horaires_ouverture
%p
  %b Capacite:
  = @salle.capacite
%p
  %b Tarif minimum:
  = @salle.tarif_minimum
%p
  %b Activites:
  = @salle.activites
%p
  %b Precisions:
  = @salle.precisions

= link_to 'Edit', edit_salle_path(@salle)
\|
= link_to 'Back', salles_path