config/routes.rb
Rails.application.routes.draw do
  post 'salles/cree_et_ajoute_dans_meme_lieu', to: 'salles#cree_et_ajoute', as: :cree_salle_et_ajoute_dans_meme_lieu
  root 'pages#home'
  get 'a-propos', to: 'pages#apropos'
  get 'stats', to: 'pages#stats'

  resources :salles do
    collection do
      get 'brut'
      get 'prospects'
      get 'prequalifiees'
    end
  end
  get 'salles/:id/contact/:demande_id', to: 'salles#contact', as: :contacte_demandeur
  resources :propositions_salles, only: [:new, :create]
  resource :salles_import, only: [:new, :create]

  resources :demandes, only: [:new, :create, :show, :index], param: :secret_id
  post 'demandes/:secret_id/cloture', to: 'demandes#cloture', as: :cloture_demande
  get 'demandes/:secret_id/autres_salles_correspondantes', to: 'demandes#autres_salles_correspondantes', as: :autres_salles_correspondantes
  post 'demandes/:secret_id/notifie/:salle_id', to: 'demandes#notifie', as: :notifie_demande
  mount LetterOpenerWeb::Engine, at: '/mails'
end

app/models/demande.rb
class Demande < ApplicationRecord
  before_create :generate_secret_id, :calcule_coordonnees!
  validates :nom_demandeur, :tel_demandeur, :email_demandeur, :nom_association,
    :date, :duree, :nb_participants, :activite, presence: true

  has_many :notifications
  has_many :contacts
  scope :en_cours, -> { order(created_at: :desc).where(cloture_le: nil) }
  scope :cloturees, -> { order(created_at: :desc).where.not(cloture_le: nil) }
  def to_param
    self.secret_id
  end

  def calcule_coordonnees!
    coordonnees = GeocoderAdresse.new("#{self.quartier}, Paris").call
    if coordonnees[:latitude].present? && coordonnees[:longitude].present?
      self.latitude = coordonnees[:latitude]
      self.longitude = coordonnees[:longitude]
    end
  end

  def statut
    return :a_traiter if a_traiter?
    return :a_contacter if a_contacter?
    return :contactee if contactee?
  end

  def contactee?
    self.contacts_count > 0
  end

  def a_contacter?
    self.contacts_count == 0
  end

  def a_traiter?
    self.notifications_count == 0
  end

  def cloturee?
    self.cloture_le.present?
  end

  def cloture!
    self.cloture_le = DateTime.now
    self.save!
  end

  def geocoded?
    self.latitude.present? && self.longitude.present?
  end

  private
  def generate_secret_id
    self.secret_id = Digest::SHA1.hexdigest "#{email_demandeur},#{Time.now.to_f}"
  end
end

app/controllers/demandes_controller.rb
class DemandesController < ApplicationController
  http_basic_authenticate_with name: ENV['ADMIN_USER'], password: ENV['ADMIN_PASSWORD'], only: [:index]

  before_action :standby, only: [:new, :create]
  before_action :set_demande, only: [:show, :cloture, :notifie, :autres_salles_correspondantes]

  def standby
    if ENV["STANDBY"] == "true"
      redirect_to root_path
    end
  end

  def new
    @demande = Demande.new
  end

  def create
    @demande = Demande.new(demande_params)

    if @demande.save
      DemandeMailer.confirm(@demande).deliver
    else
      render :new
    end
  end

  def show
    if admin?
      matcher = MatcherSalles.new(@demande)
      matcher.cherche!
      @salles_correspondantes = matcher.salles
      @autres_salles_correspondantes = matcher.autres_salles_correspondantes?
      @limite = 2 * MatcherSalles::LIMITE_PROPOSITION
      render :show_admin
    else
      render :show_demandeur
    end
  end

  def index
    @demandes_en_cours = Demande.en_cours
    @demandes_cloturees = Demande.cloturees
  end

  def cloture
    @demande.cloture!
    if admin?
      redirect_to demandes_path
    else
      render 'cloturee'
    end
  end

  def notifie
    salle = Salle.find(params[:salle_id])
    NotifierSalle.new(@demande, salle).call!
    redirect_to @demande
  end

  def autres_salles_correspondantes
    if admin?
      if params[:limite]
        limite = params[:limite].to_i
        matcher = MatcherSalles.new(@demande, limite)
      else
        limite = 0
        matcher = MatcherSalles.new(@demande)
      end
      matcher.cherche!
      @salles_correspondantes = matcher.salles
      @autres_salles_correspondantes = matcher.autres_salles_correspondantes?
      @limite = limite + MatcherSalles::LIMITE_PROPOSITION
      render :show_admin
    else
      redirect_to root_path
    end
  end

  private
    def set_demande
      @demande = Demande.find_by_secret_id(params[:secret_id])
    end

    def demande_params
      params.require(:demande).permit(:nom_demandeur, :tel_demandeur, :email_demandeur, :nom_association, :date, :duree, :nb_participants, :objet, :activite, :quartier)
    end
end

app/views/demandes/_form.html.haml
= form_for @demande, html: { class: 'ui large form container demande' } do |f|
  - if @demande.errors.any?
    #explication_erreurs.ui.negative.message
      .header= "Impossible de déposer cette demande"
      %ul.list
        - @demande.errors.full_messages.each do |message|
          %li= message
  .equal.width.fields
    .required.field
      = f.label :nom_association, "Nom de l'association"
      = f.text_field :nom_association
    .required.field
      = f.label :nom_demandeur, 'Votre nom'
      = f.text_field :nom_demandeur
  .inline.fields
    .required.eight.wide.field
      = f.label :tel_demandeur, 'Votre téléphone'
      = f.text_field :tel_demandeur
    .required.eight.wide.field
      = f.label :email_demandeur, 'Votre email'
      = f.text_field :email_demandeur

  .inline.fields
    .required.eight.wide.field
      = f.label :date, 'A quelle date souhaitez-vous réserver une salle ?'
      = f.text_field :date
    .required.eight.wide.field
      = f.label :duree, 'A quelle heure ?'
      = f.text_field :duree, placeholder: 'De 19h à 21h'
  .inline.fields
    .required.field
      = f.label :nb_participants, 'Nombre de participants'
      = f.number_field :nb_participants

  %h5 Disposition de la salle
  .inline.fields
    .field
      = f.radio_button :disposition, :sans_preference, checked: true
      = f.label :disposition_avec_table, 'Sans préférence'
    .field
      = f.radio_button :disposition, :avec_tables
      = f.label :disposition_avec_table, 'Réunion (Avec tables)'

    .field
      = f.radio_button :disposition, :theatre
      = f.label :disposition_theatre, 'Assemblée (Avec chaises + tribune)'
  .required.field
    = f.label :activite, "Que souhaitez-vous faire dans la salle ?"
    = f.text_area :activite, rows: 2, placeholder: "Assemblée Générale, Répétition théâtre, ..."
  .field
    = f.label :quartier, "A proximité de quelle adresse ou quel quartier souhaitez-vous une salle ?"
    = f.text_field :quartier
  %p.hint
    %i L'équipe de Vite un lieu vous conseille d'ajouter le plus de précisions possibles.L'expérience montre que plus une demande est précise, plus elle a de chances d'avoir une réponse rapidement.
  .actions
    = f.submit 'Déposer la demande', class: 'ui submit button fluid teal huge'

app/views/demandes/cloturee.html.haml
.ui.grid.container.main.relaxed
  .ui.stacked.segment.attached.huge
    %p
      Votre demande vient d'être clôturée
      Merci d'avoir fait confiance à l'équipe de
      %i Vite un lieu

app/views/demandes/create.html.haml
.ui.grid.container.main.relaxed
  .ui.stacked.segment.attached.huge
    %p
      Votre demande a bien été déposée.
      L'équipe de
      %i Vite un lieu
      se met en quête de la salle dont vous avez besoin. Nous revenons vite vers vous pour vous faire une proposition.

app/views/demandes/edit.html.haml
%h1 Editing demande

= render 'form'

= link_to 'Show', @demande
\|
= link_to 'Back', demandes_path

app/views/demandes/index.html.haml
.ui.main.container.relaxed
  %h1 Demandes déposées

  #demandes-menu.ui.top.attached.tabular.menu
    %a.item.active{"data-tab": 'en-cours'} En cours
    %a.item{"data-tab": 'cloturees'} Clôturées
  .ui.bottom.attached.tab.segment.active{"data-tab": 'en-cours'}
    %table.ui.fixed.table
      %thead
        %tr
          %th Déposé le
          %th Nom association
          %th Date
          %th Duree
          %th Nb participants
          %th Notifications
          %th Contacts
          %th.four.wide Actions

      %tbody.demandes-en-cours
        - @demandes_en_cours.each do |demande|
          %tr{class: "demande #{demande.statut}"}
            %td= l(demande.created_at, format: :short)
            %td= demande.nom_association
            %td= demande.date
            %td= demande.duree
            %td= demande.nb_participants
            %td= demande.notifications_count
            %td= demande.contacts_count
            %td
              = link_to cloture_demande_path(demande.secret_id),method: :post do
                %button.ui.warning.button Cloturer
              = link_to demande_path(demande.secret_id) do
                %button.ui.primary.button Traîter
  .ui.bottom.attached.tab.segment{"data-tab": 'cloturees'}
    %table.ui.striped.fixed.table
      %thead
        %tr
          %th Déposé le
          %th Nom demandeur
          %th Nom association
          %th Date
          %th Duree
          %th Nb participants
          %th Budget
          %th Activite
          %th Clôturé le

      %tbody.demandes-cloturees
        - @demandes_cloturees.each do |demande|
          %tr.demande
            %td= link_to l(demande.created_at, format: :short), demande
            %td= demande.nom_demandeur
            %td= demande.nom_association
            %td= demande.date
            %td= demande.duree
            %td= demande.nb_participants
            %td= demande.budget
            %td= truncate(demande.activite)
            %td= l(demande.cloture_le, format: :short)

app/views/demandes/new.html.haml
.ui.main.container.relaxed
  %h2 Votre demande
  = render 'form'

app/views/demandes/show_admin.html.haml
.ui.container.main.relaxed
  .ui.stackable.grid
    .five.wide.column
      .demande.ui.card
        .content
          .header= "Demande de salle déposée le #{l(@demande.created_at.to_date)}"
          - if @demande.cloturee?
            .header= "Demande clôturée le #{l(@demande.cloture_le.to_date)}"
          .meta
            = "#{@demande.nom_association} (#{@demande.nom_demandeur})"
          .meta= @demande.email_demandeur
          .meta= @demande.tel_demandeur
          .description
            = @demande.nb_participants
            participants
            %br
            Date :
            = @demande.date
            %br
            Duree :
            = @demande.duree
            %br
            Budget :
            = @demande.budget
            €
            %br
            Precisions :
            = @demande.activite
        - unless @demande.cloturee?
          .extra.content
            = link_to cloture_demande_path(@demande), method: :post do
              .ui.basic.teal.button Clôturer la demande
    .eleven.wide.column
      %header.header
        %h1 Salles correspondantes
        - if @autres_salles_correspondantes
          = link_to autres_salles_correspondantes_path(@demande, limite: @limite) do
            .ui.basic.teal.button Proposer des salles supplémentaires
      %table.ui.striped.table
        %thead
          %tr
            %th
            %td Nom
            %td Capacité
            %td Tarif minimum
            %td Tel
            %td Adresse
        %tbody.salles.correspondantes
          - @salles_correspondantes.each do |salle|
            %tr{id: "salle-#{salle.id}"}
              %td
                = action_ou_evenements_pour_salle(salle, @demande)
              %td= salle.nom
              %td= salle.capacite
              %td= salle.tarif_minimum
              %td= salle.tel
              %td= salle.adresse

app/views/demandes/show_demandeur.html.haml
.ui.container.main.relaxed
  .ui.stackable.grid
    .five.wide.column
      .demande.ui.card
        .content
          .header= "Demande de salle déposée le #{l(@demande.created_at.to_date)}"
          - if @demande.cloturee?
            .header= "Demande clôturée le #{l(@demande.cloture_le.to_date)}"
          .meta
            = "#{@demande.nom_association} (#{@demande.nom_demandeur})"
          .meta= @demande.email_demandeur
          .meta= @demande.tel_demandeur
          .description
            = @demande.nb_participants
            participants
            %br
            Date :
            = @demande.date
            %br
            Duree :
            = @demande.duree
            %br
            Budget :
            = @demande.budget
            €
            %br
            Precisions :
            = @demande.activite
        - unless @demande.cloturee?
          .extra.content
            = link_to cloture_demande_path(@demande), method: :post do
              .ui.basic.teal.button Clôturer la demande