config/routes.rb
Rails.application.routes.draw do
  post 'salles/cree_et_ajoute_dans_meme_lieu', to: 'salles#cree_et_ajoute', as: :cree_salle_et_ajoute_dans_meme_lieu
  root 'pages#home'
  get 'a-propos', to: 'pages#apropos'
  get 'stats', to: 'pages#stats'

  resources :salles do
    collection do
      get 'brut'
      get 'prospects'
      get 'prequalifiees'
    end
  end
  get 'salles/:id/contact/:demande_id', to: 'salles#contact', as: :contacte_demandeur
  resources :propositions_salles, only: [:new, :create]
  resource :salles_import, only: [:new, :create]

  resources :demandes, only: [:new, :create, :show, :index], param: :secret_id
  post 'demandes/:secret_id/cloture', to: 'demandes#cloture', as: :cloture_demande
  get 'demandes/:secret_id/autres_salles_correspondantes', to: 'demandes#autres_salles_correspondantes', as: :autres_salles_correspondantes
  post 'demandes/:secret_id/notifie/:salle_id', to: 'demandes#notifie', as: :notifie_demande
  mount LetterOpenerWeb::Engine, at: '/mails'
end

app/views/layouts/_footer.html.haml
%footer.ui.inverted.vertical.footer.segment
  .ui.container
    .ui.stackable.inverted.divided.equal.height.stackable.grid
      .three.wide.column
        %h4.ui.inverted.header A propos
        .ui.inverted.link.list
          = link_to "Qui sommes-nous ?", a_propos_path, class: 'item'
          = link_to "Statistiques", stats_path, class: 'item'
          = link_to "Espace administration", demandes_path, class: 'item'
      .seven.wide.column
        %h4.ui.inverted.header Version expérimentale
        %p La plateforme "Vite, un lieu" est en version expérimentale, dans le cadre du programme Startup de Ville de la ville de Paris

app/views/layouts/_header.html.haml
%header.ui.fixed.inverted.menu
  .ui.container
    %a.header.item{:href => "/"}
      = image_tag("logo.png", class: "logo")
      Vite, un lieu !
    = item_link_to "A propos", a_propos_path
    - if admin?
      .right.menu
        = item_link_to 'Demandes', demandes_path
        = item_link_to 'Salles', salles_path

app/views/layouts/_messages.html.haml
.ui.container.messages
  - if notice
    .ui.positive.icon.message
      %i.info.icon
      .content
        = notice
  - if alert
    .ui.negative.icon.message
      %i.warning.icon
      .content
        = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Vite, un lieu !
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    = yield
    = render 'layouts/footer'
    = javascript_include_tag 'application'

app/views/layouts/landing.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Vite, un lieu !
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .pusher
      = yield
      = render 'layouts/footer'